#ifndef TEST_UTILS_JSON_GETJSONVALUEFROMSTRING_H
#define TEST_UTILS_JSON_GETJSONVALUEFROMSTRING_H

#include <check.h>

TCase* test_case_getJSONValueFromString();

#endif  // TEST_UTILS_JSON_GETJSONVALUEFROMSTRING_H
