#ifndef TEST_UTILS_JSON_GETJSONVALUESFROMSTRING_H
#define TEST_UTILS_JSON_GETJSONVALUESFROMSTRING_H

#include <check.h>

TCase* test_case_getJSONValuesFromString();

#endif  // TEST_UTILS_JSON_GETJSONVALUESFROMSTRING_H
