#ifndef TEST_UTILS_JSON_MERGEJSONOBJECTSTRINGS_H
#define TEST_UTILS_JSON_MERGEJSONOBJECTSTRINGS_H

#include <check.h>

TCase* test_case_mergeJSONObjectStrings();

#endif  // TEST_UTILS_JSON_MERGEJSONOBJECTSTRINGS_H
