#!/bin/bash

_oidc-agent() {
	local cur prev opts
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	local IFS=$'\t\n'
  _getOptions "oidc-agent"

	if [[ ${cur} == * ]] ; then
    local IFS=$'#\n'
		COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
		return 0
	fi
	return 0
}

complete -o nospace -F _oidc-agent oidc-agent
