#ifndef TEST_UTILS_STRINGUTILS_STRSUBSTRINGCASE_H
#define TEST_UTILS_STRINGUTILS_STRSUBSTRINGCASE_H

#include <check.h>

TCase* test_case_strSubStringCase();

#endif  // TEST_UTILS_STRINGUTILS_STRSUBSTRINGCASE_H
