#ifndef TEST_UTILS_CRYPT_MEMORYCRYPT_INITMEMORYCRYPT_H
#define TEST_UTILS_CRYPT_MEMORYCRYPT_INITMEMORYCRYPT_H

#include <check.h>

TCase* test_case_initMemoryCrypt();

#endif  // TEST_UTILS_CRYPT_MEMORYCRYPT_INITMEMORYCRYPT_H
