site_name: oidc-agent Documentation
repo_url: https://github.com/indigo-dc/oidc-agent
theme:
  name: material
  palette:
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.integrate
    - content.code.copy
  navigation_depth: 4
  hljs_languages:
    - shell session
    - yaml
    - json
markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - abbr
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search
  - awesome-pages:
      collapse_single_pages: true
  - macros
  - social
  - privacy
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/indigo-dc/oidc-agent
    - icon: material/package
      link: http://repo.data.kit.edu
    - icon: octicons/mail-24
      link: mailto:oidc-agent-contact@lists.kit.edu
  generator: false
copyright: Copyright &copy; 2017 - 2025 KIT
nav:
  - Introduction: index.md
  - Quickstart: quickstart.md
  - Migrating to oidc-agent 5: oidc-agent5.md
  - Installation:
      - Linux: installation/install.md
      - MacOS: installation/macos.md
      - Windows: installation/windows.md
  - Configuration:
      - oidc-agent Directory: configuration/directory.md
      - General Configuration: configuration/config.md
      - Default Accounts: configuration/default-accounts.md
      - Custom Request Parameter: configuration/custom-parameters.md
      - Configuration of Providers: configuration/issuers.md
      - oidc-agent Integration: configuration/integration.md
      - Agent Forwarding: configuration/forwarding.md
  - Usage:
      - Introduction: usage/index.md
      - oidc-agent:
          - Summary: usage/oidc-agent/index.md
          - Starting oidc-agent: usage/oidc-agent/start.md
          - General Usage: usage/oidc-agent/general.md
          - Detailed Information About All Options: usage/oidc-agent/options.md
      - oidc-agent-service: usage/oidc-agent-service/index.md
      - oidc-keychain:
          - Summary: usage/oidc-keychain/index.md
          - General Usage: usage/oidc-keychain/general.md
          - Detailed Information About All Options: usage/oidc-keychain/options.md
      - oidc-gen:
          - Summary: usage/oidc-gen/index.md
          - General Usage: usage/oidc-gen/general.md
          - Detailed Information About All Options: usage/oidc-gen/options.md
          - Integrate With Different Providers:
              - Introduction: provider/index.md
              - B2Access: provider/b2access.md
              - EGI: provider/egi.md
              - Elixir: provider/elixir.md
              - Google: provider/google.md
              - Helmholtz AAI: provider/helmholtz.md
              - IAM  INDIGO/DEEP: provider/iam.md
              - KIT: provider/kit.md
              - Any Other Provider: provider/general.md
              - Known Issues: provider/known-issues.md
              - Client Configuration Values: provider/client-configuration-values.md
      - oidc-add:
          - Summary: usage/oidc-add/index.md
          - General Usage: usage/oidc-add/general.md
          - Detailed Information About All Options: usage/oidc-add/options.md
      - oidc-token:
          - Summary: usage/oidc-token/index.md
          - General Usage: usage/oidc-token/general.md
          - Detailed Information About All Options: usage/oidc-token/options.md
      - oidc-tokensh:
          - General Usage: usage/oidc-tokensh/general.md
          - Detailed Information About All Options: usage/oidc-tokensh/options.md
      - Other Applications Using oidc-agent: api/agent-clients.md
      - Tips: tips.md
      - oidc-agent-server: oidc-agent-server/oidc-agent-server.md
  - Windows:
      - Introduction: windows/index.md
      - Installation: windows/installation.md
  - MAC OS:
      - Introduction: macos/index.md
      - State of Feature Support: macos/state.md
      - Installation: macos/installation.md
  - Security:
      - Introduction: security/index.md
      - "Privilege Separation & Architecture": security/privilege-separation.md
      - Account Configuration Files: security/account-configs.md
      - Credentials: security/credentials.md
      - Memory: security/memory.md
      - Agent Locking: security/agent-locking.md
      - Communication: security/communication.md
      - Encryption Passwords: security/encryption-passwords.md
      - Autounload  Lifetime: security/autounload.md
      - User Confirmation: security/confirmation.md
      - Tracing: security/tracing.md
      - seccomp: security/seccomp.md
      - Final Note: security/final.md
  - API:
      - Introduction: api/index.md
      - liboidc-agent5: api/api-c.md
      - liboidcagent-go: api/api-go.md
      - liboidcagent-py: api/api-py.md
      - IPC-API: api/api-ipc.md
