#ifndef TEST_UTILS_URIUTILS_ISVALIDAUTHENDPOINTURL_H
#define TEST_UTILS_URIUTILS_ISVALIDAUTHENDPOINTURL_H

#include <check.h>

TCase* test_case_isValidAuthEndpointUrl();

#endif  // TEST_UTILS_URIUTILS_ISVALIDAUTHENDPOINTURL_H
