name: Deploy MkDocs documentation

on:
  push:
    branches: [ prerel ]
    paths:
      - 'docs/**'
      - 'logo.png'
      - 'workflows/mkdocs.yml'

permissions:
  contents: write  # Needed to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs and theme
        run: |
          pip install mkdocs mkdocs-material mkdocs-macros-plugin mkdocs-awesome-pages-plugin mkdocs-material[imaging] markdown-exec[ansi]

      - name: Deploy docs to GitHub Pages
        run: cd docs && mkdocs gh-deploy --force