#ifndef TEST_OIDC_AGENT_OIDCD_JOSE_JOSEUTILS_CJOSE_GETENCRYPTHEADER_H
#define TEST_OIDC_AGENT_OIDCD_JOSE_JOSEUTILS_CJOSE_GETENCRYPTHEADER_H

#include <check.h>

TCase* test_case_cjose_getEncryptHeader();

#endif  // TEST_OIDC_AGENT_OIDCD_JOSE_JOSEUTILS_CJOSE_GETENCRYPTHEADER_H
