#ifndef TEST_OIDC_AGENT_OIDCD_JOSE_JOSEUTILS_CREATERSAKEYS_H
#define TEST_OIDC_AGENT_OIDCD_JOSE_JOSEUTILS_CREATERSAKEYS_H

#include <check.h>

TCase* test_case_createRSAKeys();

#endif  // TEST_OIDC_AGENT_OIDCD_JOSE_JOSEUTILS_CREATERSAKEYS_H
