#ifndef TEST_OIDC_AGENT_OIDCD_JOSE_JOSEUTILS_CJOSE_GETSIGNHEADER_H
#define TEST_OIDC_AGENT_OIDCD_JOSE_JOSEUTILS_CJOSE_GETSIGNHEADER_H

#include <check.h>

TCase* test_case_cjose_getSignHeader();

#endif  // TEST_OIDC_AGENT_OIDCD_JOSE_JOSEUTILS_CJOSE_GETSIGNHEADER_H
