#ifndef TEST_OIDC_AGENT_OIDCD_JOSE_JOSEUTILS_JOSE_ENCRYPT_H
#define TEST_OIDC_AGENT_OIDCD_JOSE_JOSEUTILS_JOSE_ENCRYPT_H

#include <check.h>

TCase* test_case_jose_encrypt();

#endif  // TEST_OIDC_AGENT_OIDCD_JOSE_JOSEUTILS_JOSE_ENCRYPT_H
