#ifndef TEST_OIDC_AGENT_OIDCD_JOSE_JOSEUTILS_JOSE_SIGN_H
#define TEST_OIDC_AGENT_OIDCD_JOSE_JOSEUTILS_JOSE_SIGN_H

#include <check.h>

TCase* test_case_jose_sign();

#endif  // TEST_OIDC_AGENT_OIDCD_JOSE_JOSEUTILS_JOSE_SIGN_H
