#ifndef TEST_OIDC_AGENT_OIDCD_JOSE_JOSEUTILS_JOSE_SIGNANDENCRYPT_H
#define TEST_OIDC_AGENT_OIDCD_JOSE_JOSEUTILS_JOSE_SIGNANDENCRYPT_H

#include <check.h>

TCase* test_case_jose_signAndEncrypt();

#endif  // TEST_OIDC_AGENT_OIDCD_JOSE_JOSEUTILS_JOSE_SIGNANDENCRYPT_H
